name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
      - name: Run e2e tests
        run: |
          npm cypress run --env ENV=${{ inputs.environment }} --browser electron --record
        env:
          CYPRESS_INCLUDE_TAGS: smoke